twig:
    globals: 
        developer: "EECKHOUT RÃ©mi"
        contact: "r.eeckhout@amiens-metropole.com"
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
